//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SpartaDominio;
    
    public partial class SpartaEntities : DbContext
    {
        public SpartaEntities()
            : base("name=SpartaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<ActividadEconomica> ActividadEconomica { get; set; }
        public virtual DbSet<BibliotecaPregunta> BibliotecaPregunta { get; set; }
        public virtual DbSet<CategoriaPremio> CategoriaPremio { get; set; }
        public virtual DbSet<Causa> Causa { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Cobertura> Cobertura { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<DetalleParametro> DetalleParametro { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<DocumentosRelacionados> DocumentosRelacionados { get; set; }
        public virtual DbSet<DocumentoUsuario> DocumentoUsuario { get; set; }
        public virtual DbSet<Funcionalidad> Funcionalidad { get; set; }
        public virtual DbSet<Inmueble_PYME> Inmueble_PYME { get; set; }
        public virtual DbSet<Insignia> Insignia { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
        public virtual DbSet<Mascota> Mascota { get; set; }
        public virtual DbSet<Nivel> Nivel { get; set; }
        public virtual DbSet<Notificacion> Notificacion { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Parametro> Parametro { get; set; }
        public virtual DbSet<ParticipanteReto> ParticipanteReto { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Poliza> Poliza { get; set; }
        public virtual DbSet<PostVenta> PostVenta { get; set; }
        public virtual DbSet<Preliquidacion> Preliquidacion { get; set; }
        public virtual DbSet<Premio> Premio { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Redencion> Redencion { get; set; }
        public virtual DbSet<RespuestaPregunta> RespuestaPregunta { get; set; }
        public virtual DbSet<Reto> Reto { get; set; }
        public virtual DbSet<RetoUsuario> RetoUsuario { get; set; }
        public virtual DbSet<Riesgo> Riesgo { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Tema> Tema { get; set; }
        public virtual DbSet<UnidadComercial> UnidadComercial { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<ContenidoReto> ContenidoReto { get; set; }
        public virtual DbSet<FuncionalidadPorRol> FuncionalidadPorRol { get; set; }
        public virtual DbSet<LogProceso> LogProceso { get; set; }
        public virtual DbSet<NotificacionUsuario> NotificacionUsuario { get; set; }
        public virtual DbSet<ParticipantePremio> ParticipantePremio { get; set; }
        public virtual DbSet<PersonaPoliza> PersonaPoliza { get; set; }
        public virtual DbSet<PersonaProducto> PersonaProducto { get; set; }
        public virtual DbSet<RepresentanteLegal> RepresentanteLegal { get; set; }
    }
}
