//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_producto_suministro
    {
        public int id_producto { get; set; }
        public Nullable<int> id_suministro { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> estado { get; set; }
        public long id_producto_suministro { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual suministro suministro { get; set; }
    }
}
