//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public long Id_empleado { get; set; }
        public string n_identificacion { get; set; }
        public Nullable<int> id_tipo_documento { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> empleado_id_rol { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string barrio { get; set; }
        public string estado { get; set; }
    
        public virtual rol rol { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
    }
}
