//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public long id_evento { get; set; }
        public Nullable<long> solicitud_id_solicitud { get; set; }
        public Nullable<long> cliente_id_cliente { get; set; }
        public Nullable<int> tipo_evento { get; set; }
        public Nullable<int> id_lugar { get; set; }
        public Nullable<int> cantidad_personas { get; set; }
        public Nullable<int> cantidad_meseros { get; set; }
        public Nullable<System.DateTime> hora_inicio { get; set; }
        public Nullable<System.DateTime> hora_fin { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> estado_evento { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual estado_evento estado_evento1 { get; set; }
        public virtual lugar lugar { get; set; }
        public virtual solicitud solicitud { get; set; }
        public virtual tipo_evento tipo_evento1 { get; set; }
    }
}
