//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int id_pedido { get; set; }
        public Nullable<int> producto_id_producto { get; set; }
        public Nullable<int> proveedor_id_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_pedido { get; set; }
        public string cantidad { get; set; }
        public Nullable<int> id_medida_producto { get; set; }
        public string observaciones { get; set; }
        public string fecha_sugerida { get; set; }
        public string estado { get; set; }
    
        public virtual medida_producto medida_producto { get; set; }
        public virtual producto producto { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
