//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitud
    {
        public long id_solicitud { get; set; }
        public string nombre_cliente { get; set; }
        public Nullable<int> cantidad_personas { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<int> id_tipo_evento { get; set; }
        public string hora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
        public Nullable<bool> visto { get; set; }
    
        public virtual tipo_evento tipo_evento { get; set; }
    }
}
