//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class suministro
    {
        public int id_suministro { get; set; }
        public string nombre { get; set; }
        public string foto { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> cantidad_minima { get; set; }
        public Nullable<int> medida { get; set; }
        public Nullable<decimal> precio_unidad { get; set; }
        public string observaciones { get; set; }
        public string estado { get; set; }
    
        public virtual medida_producto medida_producto { get; set; }
    }
}
