//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContenidoReto
    {
        public long FKReto { get; set; }
        public long Producto { get; set; }
        public Nullable<int> Tema { get; set; }
        public Nullable<long> Libro { get; set; }
    
        public virtual Reto Reto { get; set; }
    }
}
