//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int IdDireccion { get; set; }
        public long FKPersona { get; set; }
        public int TipoDireccion { get; set; }
        public int TipoCalle { get; set; }
        public string Barrio { get; set; }
        public int Ubicacion { get; set; }
        public string Observaciones { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string NumeroAvPrincipal { get; set; }
        public string NumeorAvSecundario { get; set; }
        public string NumeroCasa { get; set; }
        public string Indicador1 { get; set; }
        public string Indicador2 { get; set; }
        public string Indicador3 { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
