//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncionalidadPorRol
    {
        public int FKFuncionalidad { get; set; }
        public int FKRol { get; set; }
        public int Estado { get; set; }
    
        public virtual Funcionalidad Funcionalidad { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
