//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insignia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insignia()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdInsignia { get; set; }
        public string DescripcionInsignia { get; set; }
        public string Icono { get; set; }
        public long ValorMonedaConocimiento { get; set; }
        public long ValorMonedaComercial { get; set; }
        public int Rol { get; set; }
        public Nullable<int> Desencadenador { get; set; }
        public bool Editable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
