//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Notificacion()
        {
            this.NotificacionUsuario = new HashSet<NotificacionUsuario>();
        }
    
        public long IdNotificacion { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public int TipoNotificacion { get; set; }
        public string Icono { get; set; }
        public string ArchivoAdjunto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionUsuario> NotificacionUsuario { get; set; }
    }
}
