//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaProducto
    {
        public long FKPersona { get; set; }
        public long FKProducto { get; set; }
        public int Estado { get; set; }
        public string Observacion { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
