//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Direccion1 = new HashSet<Direccion>();
            this.PersonaPoliza = new HashSet<PersonaPoliza>();
            this.PersonaProducto = new HashSet<PersonaProducto>();
            this.Redencion = new HashSet<Redencion>();
            this.RepresentanteLegal = new HashSet<RepresentanteLegal>();
            this.RepresentanteLegal1 = new HashSet<RepresentanteLegal>();
            this.Usuario = new HashSet<Usuario>();
            this.RetoUsuario = new HashSet<RetoUsuario>();
        }
    
        public long IdPersona { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public int TipoDocumento { get; set; }
        public string NumDocumento { get; set; }
        public int Telefono { get; set; }
        public Nullable<int> Celular { get; set; }
        public string Direccion { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int TipoPersona { get; set; }
        public string Correo { get; set; }
        public int Estado { get; set; }
        public int FKActividadEconomica { get; set; }
        public string LugarNacimiento { get; set; }
        public int Sexo { get; set; }
        public Nullable<System.DateTime> FechaEstado { get; set; }
        public int FKCiudad { get; set; }
        public Nullable<int> ConsecutivoSucursal { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> VigenciaDesde { get; set; }
        public int FKUnidadComercial { get; set; }
        public Nullable<System.DateTime> VigenciaHasta { get; set; }
        public string DatoAdicional1 { get; set; }
        public string DatoAdicional2 { get; set; }
        public string DatoAdicional3 { get; set; }
        public string DatoAdicional4 { get; set; }
        public string DatoAdicional5 { get; set; }
        public string DatoAdicional6 { get; set; }
    
        public virtual ActividadEconomica ActividadEconomica { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion1 { get; set; }
        public virtual UnidadComercial UnidadComercial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaPoliza> PersonaPoliza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaProducto> PersonaProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redencion> Redencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepresentanteLegal> RepresentanteLegal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepresentanteLegal> RepresentanteLegal1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetoUsuario> RetoUsuario { get; set; }
    }
}
