//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poliza()
        {
            this.PersonaPoliza = new HashSet<PersonaPoliza>();
            this.Venta = new HashSet<Venta>();
        }
    
        public long IdPoliza { get; set; }
        public Nullable<long> NumeroPoliza { get; set; }
        public Nullable<long> NumeroCertificado { get; set; }
        public long FKProducto { get; set; }
        public Nullable<int> Estado { get; set; }
        public System.DateTime FechaExpedicion { get; set; }
        public System.DateTime FechaVigencia { get; set; }
        public long ValorPrima { get; set; }
        public int IVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaPoliza> PersonaPoliza { get; set; }
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
