//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostVenta
    {
        public long IdPostVenta { get; set; }
        public string FKVenta { get; set; }
        public int TipoSolicitud { get; set; }
        public System.DateTime Fecha { get; set; }
        public string RespuestaSolicitud { get; set; }
    
        public virtual Venta Venta { get; set; }
    }
}
