//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Premio()
        {
            this.ParticipantePremio = new HashSet<ParticipantePremio>();
            this.Redencion = new HashSet<Redencion>();
        }
    
        public long IdPremio { get; set; }
        public string NombrePremio { get; set; }
        public string DescripcionPremio { get; set; }
        public string ImagenPremio { get; set; }
        public int FKCategoriaPremio { get; set; }
        public Nullable<int> FKRol { get; set; }
        public Nullable<long> ValorComercial { get; set; }
        public Nullable<long> ValorConocimiento { get; set; }
        public int Estado { get; set; }
        public int UnidadesDisponibles { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int NumDiasEntrega { get; set; }
    
        public virtual CategoriaPremio CategoriaPremio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantePremio> ParticipantePremio { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Redencion> Redencion { get; set; }
    }
}
