//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestaPregunta
    {
        public long IdRespuesta { get; set; }
        public long FKPregunta { get; set; }
        public string DescripcionRespuesta { get; set; }
        public bool Verdadera { get; set; }
    
        public virtual BibliotecaPregunta BibliotecaPregunta { get; set; }
    }
}
