//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reto()
        {
            this.ParticipanteReto = new HashSet<ParticipanteReto>();
            this.ContenidoReto = new HashSet<ContenidoReto>();
            this.RetoUsuario = new HashSet<RetoUsuario>();
            this.BibliotecaPregunta = new HashSet<BibliotecaPregunta>();
        }
    
        public long IdReto { get; set; }
        public string TituloReto { get; set; }
        public string DescripcionCorta { get; set; }
        public string DescripcionLarga { get; set; }
        public string ImagenReto { get; set; }
        public int TipoReto { get; set; }
        public int FKRol { get; set; }
        public int RolGanador { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public Nullable<int> TipoGanador { get; set; }
        public Nullable<decimal> ApuestaMaxima { get; set; }
        public Nullable<int> CantidadIntentos { get; set; }
        public Nullable<int> NumeroPreguntas { get; set; }
        public Nullable<int> ValorAcierto { get; set; }
        public int PremioTotalMoneda { get; set; }
        public Nullable<int> TipoMeta { get; set; }
        public Nullable<long> ValorMeta { get; set; }
        public Nullable<int> CantidadGanadores { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipanteReto> ParticipanteReto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContenidoReto> ContenidoReto { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetoUsuario> RetoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BibliotecaPregunta> BibliotecaPregunta { get; set; }
    }
}
