//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetoUsuario
    {
        public int IdRetoUsuario { get; set; }
        public long FKReto { get; set; }
        public long FKPersona { get; set; }
        public Nullable<bool> Retador { get; set; }
        public bool Ganador { get; set; }
        public Nullable<int> TiempoMaximo { get; set; }
        public Nullable<int> TipoMoneda { get; set; }
        public Nullable<decimal> Apuesta { get; set; }
        public string Acierto { get; set; }
        public Nullable<int> TiempoRespuesta { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Reto Reto { get; set; }
    }
}
