//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Riesgo
    {
        public long IdRiego { get; set; }
        public Nullable<int> FKMascota { get; set; }
        public string FKVehiculo { get; set; }
        public Nullable<int> FKInmueble { get; set; }
        public Nullable<long> FKProducto { get; set; }
    
        public virtual Inmueble_PYME Inmueble_PYME { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
