//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.DocumentoUsuario = new HashSet<DocumentoUsuario>();
            this.Preliquidacion = new HashSet<Preliquidacion>();
            this.NotificacionUsuario = new HashSet<NotificacionUsuario>();
            this.Usuario1 = new HashSet<Usuario>();
            this.Insignia = new HashSet<Insignia>();
        }
    
        public long IdUsuario { get; set; }
        public long FKPersona { get; set; }
        public int FKRol { get; set; }
        public Nullable<int> FKNivel { get; set; }
        public Nullable<int> FKCategoria { get; set; }
        public long Padre { get; set; }
        public Nullable<long> MonedaConocimiento { get; set; }
        public Nullable<long> MonedaComercial { get; set; }
        public Nullable<long> MConocimientoConseguido { get; set; }
        public Nullable<long> MComercialConseguido { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<int> Comision { get; set; }
        public string Contrasena { get; set; }
        public string ClaveUnica { get; set; }
        public Nullable<System.DateTime> FechaEnvioClave { get; set; }
        public int EstadoClave { get; set; }
        public Nullable<int> TiempoValidez { get; set; }
        public Nullable<decimal> IP { get; set; }
        public string Observacion { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoUsuario> DocumentoUsuario { get; set; }
        public virtual Nivel Nivel { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preliquidacion> Preliquidacion { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionUsuario> NotificacionUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insignia> Insignia { get; set; }
    }
}
